//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AOEChat.Server.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatUser
    {
        public ChatUser()
        {
            this.LastUserPositions = new HashSet<LastUserPosition>();
            this.Messages = new HashSet<Message>();
        }
    
        public int ChatUserId { get; set; }
        public string UserName { get; set; }
    
        public virtual ICollection<LastUserPosition> LastUserPositions { get; set; }
        public virtual ICollection<Message> Messages { get; set; }
    }
}
